services:
  trainer:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    image: musicgen-train:latest
    container_name: musicgen-trainer
    tty: true
    shm_size: "8gb"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    working_dir: /app
    command: bash

  api:
    build:
      context: .                       # <-- use project root as context
      dockerfile: services/api/Dockerfile
    image: musicgen-api:latest
    container_name: musicgen-api
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts:rw
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - trainer

  front:
    build:
      context: ./services/front
      dockerfile: Dockerfile
    image: musicgen-front:latest
    container_name: musicgen-front
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
